# databases:
#   - name: social-petwork
#     user: social-petwork
#     plan: free
#     region: oregon

# services:
#   - type: web
#     name: social-petwork
#     plan: free
#     region: oregon
#     branch: main
#     env: ruby
#     buildCommand: ".bin/render-build.sh"
#     startCommand: "rails s"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: social-petwork
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false

databases:
  - name: social-petwork
    user: social-petwork
    plan: free
    region: oregon

services:
  - type: web
    name: social-petwork
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social-petwork
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false